# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/verilog/pipline/pipline.cache/wt [current_project]
set_property parent.project_path D:/verilog/pipline/pipline.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/verilog/pipline/pipline.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  D:/verilog/pipline/pipline.srcs/sources_1/imports/project_2/memfile.dat
  D:/verilog/pipline/pipline.srcs/sources_1/imports/multi_cycle/extend.dat
  D:/verilog/pipline/pipline.srcs/sources_1/imports/verilog/multi_cycle/multi_cycle.srcs/sources_1/imports/sources_1/imports/Desktop/ioFile.dat
}
read_verilog -library xil_defaultlib -sv {
  D:/verilog/pipline/pipline.srcs/sources_1/imports/new/IO.sv
  D:/verilog/pipline/pipline.srcs/sources_1/new/MIPS.sv
  D:/verilog/pipline/pipline.srcs/sources_1/new/alu.sv
  D:/verilog/pipline/pipline.srcs/sources_1/new/aludec.sv
  D:/verilog/pipline/pipline.srcs/sources_1/new/controller.sv
  D:/verilog/multi_cycle/multi_cycle.srcs/sources_1/imports/sources_1/new/datamemorydecoder.sv
  D:/verilog/pipline/pipline.srcs/sources_1/new/datapath.sv
  D:/verilog/pipline/pipline.srcs/sources_1/imports/verilog/mips_final/project_2.srcs/sources_1/new/dmem.sv
  D:/verilog/pipline/pipline.srcs/sources_1/new/eqcmp.sv
  D:/verilog/pipline/pipline.srcs/sources_1/new/flopenr.sv
  D:/verilog/pipline/pipline.srcs/sources_1/new/flopr.sv
  D:/verilog/pipline/pipline.srcs/sources_1/new/hazard.sv
  D:/verilog/pipline/pipline.srcs/sources_1/imports/new/imem.sv
  D:/verilog/pipline/pipline.srcs/sources_1/new/maindec.sv
  D:/verilog/pipline/pipline.srcs/sources_1/new/mux2.sv
  D:/verilog/pipline/pipline.srcs/sources_1/new/mux3.sv
  D:/verilog/pipline/pipline.srcs/sources_1/imports/new/mux7seg.sv
  D:/verilog/pipline/pipline.srcs/sources_1/new/regfile.sv
  D:/verilog/pipline/pipline.srcs/sources_1/new/shift.sv
  D:/verilog/pipline/pipline.srcs/sources_1/new/iotop.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/verilog/pipline/pipline.srcs/constrs_1/imports/Desktop/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files D:/verilog/pipline/pipline.srcs/constrs_1/imports/Desktop/Nexys4DDR_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top iotop -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef iotop.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file iotop_utilization_synth.rpt -pb iotop_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
