# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/verilog/fpga/fpga.srcs/sources_1/ip/clk65MHZ/clk65MHZ.xci
# IP: The module: 'clk65MHZ' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/verilog/fpga/fpga.srcs/sources_1/ip/clk65MHZ/clk65MHZ_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk65MHZ'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/verilog/fpga/fpga.srcs/sources_1/ip/clk65MHZ/clk65MHZ.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk65MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/verilog/fpga/fpga.srcs/sources_1/ip/clk65MHZ/clk65MHZ_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk65MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/verilog/fpga/fpga.srcs/sources_1/ip/clk65MHZ/clk65MHZ.xci
# IP: The module: 'clk65MHZ' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/verilog/fpga/fpga.srcs/sources_1/ip/clk65MHZ/clk65MHZ_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk65MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/verilog/fpga/fpga.srcs/sources_1/ip/clk65MHZ/clk65MHZ.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk65MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/verilog/fpga/fpga.srcs/sources_1/ip/clk65MHZ/clk65MHZ_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk65MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
