# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/verilog/fpga/fpga.srcs/sources_1/ip/eire/eire.xci
# IP: The module: 'eire' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/verilog/fpga/fpga.srcs/sources_1/ip/eire/eire_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eire'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/verilog/fpga/fpga.srcs/sources_1/ip/eire/eire.xci
# IP: The module: 'eire' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/verilog/fpga/fpga.srcs/sources_1/ip/eire/eire_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eire'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
